### ISSUE TITLE
line 276:next_batch(Xdata,batch_size, MissingVals = False) should never have MissingVals=True correct?

### ISSUE THREAD

**Issue by yezhengli-Mr9** [ProcessMonitoringStellenboschUniversity/IFAC-VAE-Imputation#2]
Hi sir, 
[line 276:`next_batch(Xdata,batch_size, MissingVals = False)`](https://github.com/ProcessMonitoringStellenboschUniversity/IFAC-VAE-Imputation/blob/master/main.py#L276) should never have `MissingVals=True` correct?

Otherwise,
if the loss function contains <img src="https://render.githubusercontent.com/render/math?math=\ell_{gt:\{m_{gt}=0 \} } (\hat{x}_{gt}, 0) "> where 0 is from nan/ unobserved value, how do you explain loss function  <img src="https://render.githubusercontent.com/render/math?math=\sum_{g,t}\ell_{gt:\{m_{gt}=0  \} } (\hat{x}_{gt}, x_{gt})= \sum_{g,t}\ell_{gt:\{m_{gt}=0, x_{gt}\ne 0  \} } (\hat{x}_{gt}, x_{gt}) \oplus \sum_{g,t}\ell_{gt:\{m_{gt}=0  , x_{gt} = 0\} } (\hat{x}_{gt}, 0) "> in your implementation?  

[ g is the row number and t is the column number.]

**Comment by skroon** [comment]
Hi.  I'm not sure I'm understanding your question correctly, but I'll try clarify things. Using MissingVals=True simply replaces the NaN's in random samples from Xdata by zeroes, and I agree this is not necessarily/typically a sensible thing to do.  As you have seen, we don't use this functionality in the rest of our code - it might be useful if you don't want to bias your data selection to complete records, but then you'd likely want to modify it to handle the NaNs in a smarter way than setting them to zero.

**Comment by yezhengli-Mr9** [comment]
> Hi. I'm not sure I'm understanding your question correctly, but I'll try clarify things. Using MissingVals=True simply replaces the NaN's in random samples from Xdata by zeroes, and I agree this is not necessarily/typically a sensible thing to do. As you have seen, we don't use this functionality in the rest of our code - it might be useful if you don't want to bias your data selection to complete records, but then you'd likely want to modify it to handle the NaNs in a smarter way than setting them to zero.

Hi sir,  thanks for the response and it makes sense as long as "don't use this functionality in the rest of our code".
